### PR TITLE
used java-openliberty and corrected dataset

### PR DESCRIPTION
**Pull request by j-c-berger**
Signed-off-by: Jacob Berger <jacob.berger@ibm.com>

For issue #9: https://github.com/kabanero-io/guide-codewind-getting-started/issues/9

@scottkurz, I kept generic references to application stacks and Appsody templates, but I made specific references to open liberty stacks. I corrected the dataset as well. Please let me know if anything else needs to be done. 

@SueChaplain, if these changes look good, then we can make a new repo, so I can divide the guide into 2 (separate section for VS Code and Eclipse), and then the 2 guides can be published!

### CODE REVIEW

**Comment by j-c-berger** [comment]
@jantley-ibm , tagging you for your awareness as well

**Review by SueChaplain — COMMENTED** [review]
A couple of things with the YAML markup.

- with a markdown file, the `<h1>` value is the YAML `title:`, so you don't need to have a `# title` under the markup or you get 2 titles displayed on the site.
- your permalink doesn't conform to the guidelines, so will need changing. It should also anticipate the split for this guide. 

Guidelines are:
*The naming convention for permalink is /guide/ followed by the GitHub repository name (do not include guide-)*

So how about changing the repo name to `guide-codewind-getting-started-vscode` with a permalink of `guide/codewind-getting-started-vscode` and then create the new repo for Eclipse, substituting the name. Ping me if you want help with the repo side of things.

Suggest title change also: "Getting started with Codewind and VS Code" and "Getting started with Codewind and Eclipse"- keeps the titles nice and short when you split. No need to mention Kabanero, users are already at the site.

**Comment by scottkurz** [comment]
Tagging @awisniew90  to please review

**Comment by SueChaplain** [comment]
License / copyright seems to be missing

**Comment by awisniew90** [comment]
@j-c-berger  - Thanks for making these changes. There are two additional references to the MicroProfile stack that I think should be changed: 

1. In the "Configuring Codewind to use application stacks" section
2. In the "More Learning" section. 

(Couldn't tag those lines in a review).

Other than that this looks good to me.

**Comment by j-c-berger** [comment]
See the new PR I've made with the suggested revisions: https://github.com/kabanero-io/guides/pull/2

**Comment by j-c-berger** [comment]
Closing because the revisions and changes are now reflected in this new PR: kabanero-io/guides#2

**Pull request closed without merging**
